/**
 * The "game" i18n namespace — GameScreen's own copy. Hand-type and alt-rule-toggle labels come
 * from ui-kit's existing "rules" namespace instead (reused, not duplicated) — see
 * packages/ui-kit/src/i18n/rulesResources.ts.
 */
export const GAME_RESOURCES = {
  en: {
    game: {
      you: "You",
      yourTurn: "Your turn",
      waiting: "Waiting for {{name}}…",
      dealer: "Dealer",
      trump: {
        prompt: "Choose trump",
        noTrump: "No Trump",
        openAuction: "Open Auction",
        declare: "Declare",
      },
      auction: {
        currentBid: "Current bid: {{tricks}}",
        noBids: "No bids yet",
        bidPrompt: "Your bid (tricks)",
        bidDecrease: "Lower bid",
        bidIncrease: "Raise bid",
        bid: "Bid",
        pass: "Pass",
        dealerPrompt: "Accept the bid of {{tricks}}?",
        sell: "Accept",
        keep: "Keep trump for myself",
      },
      auctionSummary: {
        declared: "{{name}} named trump directly",
        won: "{{name}} won the auction ({{tricks}} tricks)",
        trump: "Trump",
      },
      backToMenu: "Back to Menu",
      lastTrick: {
        toggle: "Last trick",
        label: "Last trick",
      },
      redeal: {
        banner: "Your hand has no face cards (J, Q, K, A) — you can request a redeal.",
        button: "Request Redeal",
      },
      gameOver: "Game Over",
      difficulty: {
        label: "Difficulty",
        easy: "Easy",
        normal: "Normal",
        hard: "Hard",
        expert: "Expert",
      },
      start: "Start Game",
      resume: {
        title: "Unfinished Game",
        body: "You have a game in progress. Resume it, or start a new one instead?",
        resume: "Resume Game",
        startNew: "Start New Game",
      },
      handComplete: {
        title: "Hand {{number}} Complete",
        continue: "Continue",
      },
      scoreboard: {
        title: "Scoreboard",
        viewButton: "View Scoreboard",
        backToTable: "Back to Table",
        total: "Total",
        negativeSubtotal: "Negative Subtotal",
        positiveSubtotal: "Positive Subtotal",
        winner: "{{name}} wins!",
        tie: "Tied: {{names}}",
        rule: {
          noTricks: "-20/trick",
          noHearts: "-20/heart",
          noGentlemen: "-30/card",
          noLady: "-50/card",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/trick",
          positiveDown: "325-75/trick",
        },
      },
    },
  },
  es: {
    game: {
      you: "Tú",
      yourTurn: "Tu turno",
      waiting: "Esperando a {{name}}…",
      dealer: "Dealer",
      trump: {
        prompt: "Elige el triunfo",
        noTrump: "Sin Triunfo",
        openAuction: "Abrir Subasta",
        declare: "Declarar",
      },
      auction: {
        currentBid: "Puja actual: {{tricks}}",
        noBids: "Aún no hay pujas",
        bidPrompt: "Tu puja (bazas)",
        bidDecrease: "Bajar puja",
        bidIncrease: "Subir puja",
        bid: "Pujar",
        pass: "Pasar",
        dealerPrompt: "¿Aceptar la puja de {{tricks}}?",
        sell: "Aceptar",
        keep: "Quedarme con el triunfo",
      },
      auctionSummary: {
        declared: "{{name}} nombró el triunfo directamente",
        won: "{{name}} ganó la subasta ({{tricks}} bazas)",
        trump: "Triunfo",
      },
      backToMenu: "Volver al Menú",
      lastTrick: {
        toggle: "Última baza",
        label: "Última baza",
      },
      redeal: {
        banner: "Tu mano no tiene figuras (J, Q, K, As) — puedes pedir cambio de juego.",
        button: "Pedir Cambio de Juego",
      },
      gameOver: "Fin del Juego",
      difficulty: {
        label: "Dificultad",
        easy: "Fácil",
        normal: "Normal",
        hard: "Difícil",
        expert: "Experto",
      },
      start: "Empezar Juego",
      resume: {
        title: "Partida sin Terminar",
        body: "Tienes una partida en curso. ¿Quieres continuarla, o empezar una nueva?",
        resume: "Continuar Partida",
        startNew: "Empezar Partida Nueva",
      },
      handComplete: {
        title: "Mano {{number}} Completa",
        continue: "Continuar",
      },
      scoreboard: {
        title: "Tabla de Resultados",
        viewButton: "Ir a Tabla de Resultados",
        backToTable: "Volver a la Mesa",
        total: "Total",
        negativeSubtotal: "Subtotal Negativo",
        positiveSubtotal: "Subtotal Positivo",
        winner: "¡{{name}} gana!",
        tie: "Empate: {{names}}",
        rule: {
          noTricks: "-20/baza",
          noHearts: "-20/corazón",
          noGentlemen: "-30/carta",
          noLady: "-50/carta",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/baza",
          positiveDown: "325-75/baza",
        },
      },
    },
  },
};
