/**
 * The "game" i18n namespace — GameScreen's own copy. Hand-type and alt-rule-toggle labels come
 * from ui-kit's existing "rules" namespace instead (reused, not duplicated) — see
 * packages/ui-kit/src/i18n/rulesResources.ts.
 */
export const GAME_RESOURCES = {
  en: {
    game: {
      you: "You",
      yourTurn: "Your turn",
      waiting: "Waiting for {{name}}…",
      dealer: "Dealer",
      trump: {
        prompt: "Choose trump",
        noTrump: "No Trump",
        openAuction: "Open Auction",
        declare: "Declare",
      },
      auction: {
        currentBid: "Current bid: {{tricks}}",
        noBids: "No bids yet",
        bidPrompt: "Your bid (tricks)",
        bidDecrease: "Lower bid",
        bidIncrease: "Raise bid",
        bid: "Bid",
        pass: "Pass",
        dealerPrompt: "Accept the bid of {{tricks}}?",
        sell: "Accept",
        keep: "Keep trump for myself",
      },
      auctionSummary: {
        declared: "{{name}} named trump directly",
        won: "{{name}} won the auction ({{tricks}} tricks)",
        trump: "Trump",
      },
      backToMenu: "Back to Menu",
      lastTrick: {
        toggle: "Last trick",
        label: "Last trick",
      },
      redeal: {
        banner: "Your hand has no face cards (J, Q, K, A) — you can request a redeal.",
        button: "Request Redeal",
      },
      illegalPlay: {
        mustFollowSuit: "You must follow suit.",
        mustBeat: "Mandatory Killing: you must beat the highest card of the led suit.",
        mustTrump: "Mandatory Killing: you must trump, since you can't follow suit.",
        heartsLocked: "You can't lead a heart until it's all you have left.",
      },
      gameOver: "Game Over",
      difficulty: {
        label: "Difficulty",
        easy: "Easy",
        normal: "Normal",
        hard: "Hard",
        expert: "Expert",
      },
      start: "Start Game",
      resume: {
        title: "Unfinished Game",
        body: "You have a game in progress. Resume it, or start a new one instead?",
        resume: "Resume Game",
        startNew: "Start New Game",
      },
      handComplete: {
        title: "Hand {{number}} Complete",
        continue: "Continue",
      },
      scoreboard: {
        title: "Scoreboard",
        viewButton: "View Scoreboard",
        backToTable: "Back to Table",
        total: "Total",
        negativeSubtotal: "Negative Subtotal",
        positiveSubtotal: "Positive Subtotal",
        winner: "{{name}} wins!",
        tie: "Tied: {{names}}",
        rule: {
          noTricks: "-20/trick",
          noHearts: "-20/heart",
          noGentlemen: "-30/card",
          noLady: "-50/card",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/trick",
          positiveDown: "325-75/trick",
        },
      },
    },
  },
  es: {
    game: {
      you: "Tú",
      yourTurn: "Tu turno",
      waiting: "Esperando a {{name}}…",
      dealer: "Dealer",
      trump: {
        prompt: "Elige el triunfo",
        noTrump: "Sin Triunfo",
        openAuction: "Abrir Subasta",
        declare: "Declarar",
      },
      auction: {
        currentBid: "Puja actual: {{tricks}}",
        noBids: "Aún no hay pujas",
        bidPrompt: "Tu puja (bazas)",
        bidDecrease: "Bajar puja",
        bidIncrease: "Subir puja",
        bid: "Pujar",
        pass: "Pasar",
        dealerPrompt: "¿Aceptar la puja de {{tricks}}?",
        sell: "Aceptar",
        keep: "Quedarme con el triunfo",
      },
      auctionSummary: {
        declared: "{{name}} nombró el triunfo directamente",
        won: "{{name}} ganó la subasta ({{tricks}} bazas)",
        trump: "Triunfo",
      },
      backToMenu: "Volver al Menú",
      lastTrick: {
        toggle: "Última baza",
        label: "Última baza",
      },
      redeal: {
        banner: "Tu mano no tiene figuras (J, Q, K, As) — puedes pedir cambio de juego.",
        button: "Pedir Cambio de Juego",
      },
      illegalPlay: {
        mustFollowSuit: "Debes seguir el palo.",
        mustBeat: "Matar Obligatorio: debes superar la carta más alta del palo jugado.",
        mustTrump: "Matar Obligatorio: debes triunfar, ya que no puedes seguir el palo.",
        heartsLocked: "No puedes lanzar un corazón hasta que sea lo único que te queda.",
      },
      gameOver: "Fin del Juego",
      difficulty: {
        label: "Dificultad",
        easy: "Fácil",
        normal: "Normal",
        hard: "Difícil",
        expert: "Experto",
      },
      start: "Empezar Juego",
      resume: {
        title: "Partida sin Terminar",
        body: "Tienes una partida en curso. ¿Quieres continuarla, o empezar una nueva?",
        resume: "Continuar Partida",
        startNew: "Empezar Partida Nueva",
      },
      handComplete: {
        title: "Mano {{number}} Completa",
        continue: "Continuar",
      },
      scoreboard: {
        title: "Tabla de Resultados",
        viewButton: "Ir a Tabla de Resultados",
        backToTable: "Volver a la Mesa",
        total: "Total",
        negativeSubtotal: "Subtotal Negativo",
        positiveSubtotal: "Subtotal Positivo",
        winner: "¡{{name}} gana!",
        tie: "Empate: {{names}}",
        rule: {
          noTricks: "-20/baza",
          noHearts: "-20/corazón",
          noGentlemen: "-30/carta",
          noLady: "-50/carta",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/baza",
          positiveDown: "325-75/baza",
        },
      },
    },
  },
  fr: {
    game: {
      you: "Toi",
      yourTurn: "À ton tour",
      waiting: "En attente de {{name}}…",
      dealer: "Donneur",
      trump: {
        prompt: "Choisis l'atout",
        noTrump: "Sans Atout",
        openAuction: "Ouvrir l'Enchère",
        declare: "Déclarer",
      },
      auction: {
        currentBid: "Enchère actuelle : {{tricks}}",
        noBids: "Aucune enchère encore",
        bidPrompt: "Ton enchère (levées)",
        bidDecrease: "Baisser l'enchère",
        bidIncrease: "Monter l'enchère",
        bid: "Enchérir",
        pass: "Passer",
        dealerPrompt: "Accepter l'enchère de {{tricks}} ?",
        sell: "Accepter",
        keep: "Garder l'atout pour moi",
      },
      auctionSummary: {
        declared: "{{name}} a nommé l'atout directement",
        won: "{{name}} a remporté l'enchère ({{tricks}} levées)",
        trump: "Atout",
      },
      backToMenu: "Retour au Menu",
      lastTrick: {
        toggle: "Dernière levée",
        label: "Dernière levée",
      },
      redeal: {
        banner: "Ta main n'a pas de figures (V, D, R, As) — tu peux demander une redistribution.",
        button: "Demander une Redistribution",
      },
      illegalPlay: {
        mustFollowSuit: "Tu dois fournir la couleur demandée.",
        mustBeat: "Obligation de Couper : tu dois battre la carte la plus haute de la couleur demandée.",
        mustTrump: "Obligation de Couper : tu dois couper, puisque tu ne peux pas fournir la couleur.",
        heartsLocked: "Tu ne peux pas entamer avec un cœur tant que ce n'est pas tout ce qu'il te reste.",
      },
      gameOver: "Fin de la Partie",
      difficulty: {
        label: "Difficulté",
        easy: "Facile",
        normal: "Normal",
        hard: "Difficile",
        expert: "Expert",
      },
      start: "Commencer la Partie",
      resume: {
        title: "Partie Inachevée",
        body: "Tu as une partie en cours. La reprendre, ou en commencer une nouvelle ?",
        resume: "Reprendre la Partie",
        startNew: "Commencer une Nouvelle Partie",
      },
      handComplete: {
        title: "Main {{number}} Terminée",
        continue: "Continuer",
      },
      scoreboard: {
        title: "Tableau des Scores",
        viewButton: "Voir le Tableau des Scores",
        backToTable: "Retour à la Table",
        total: "Total",
        negativeSubtotal: "Sous-total Négatif",
        positiveSubtotal: "Sous-total Positif",
        winner: "{{name}} gagne !",
        tie: "Égalité : {{names}}",
        rule: {
          noTricks: "-20/levée",
          noHearts: "-20/cœur",
          noGentlemen: "-30/carte",
          noLady: "-50/carte",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/levée",
          positiveDown: "325-75/levée",
        },
      },
    },
  },
  de: {
    game: {
      you: "Du",
      yourTurn: "Du bist dran",
      waiting: "Warte auf {{name}}…",
      dealer: "Geber",
      trump: {
        prompt: "Trumpf wählen",
        noTrump: "Kein Trumpf",
        openAuction: "Auktion Eröffnen",
        declare: "Ansagen",
      },
      auction: {
        currentBid: "Aktuelles Gebot: {{tricks}}",
        noBids: "Noch keine Gebote",
        bidPrompt: "Dein Gebot (Stiche)",
        bidDecrease: "Gebot senken",
        bidIncrease: "Gebot erhöhen",
        bid: "Bieten",
        pass: "Passen",
        dealerPrompt: "Gebot von {{tricks}} annehmen?",
        sell: "Annehmen",
        keep: "Trumpf für mich behalten",
      },
      auctionSummary: {
        declared: "{{name}} hat direkt Trumpf angesagt",
        won: "{{name}} hat die Auktion gewonnen ({{tricks}} Stiche)",
        trump: "Trumpf",
      },
      backToMenu: "Zurück zum Menü",
      lastTrick: {
        toggle: "Letzter Stich",
        label: "Letzter Stich",
      },
      redeal: {
        banner: "Deine Hand hat keine Bildkarten (B, D, K, As) — du kannst eine Neuverteilung verlangen.",
        button: "Neuverteilung Verlangen",
      },
      illegalPlay: {
        mustFollowSuit: "Du musst die Farbe bedienen.",
        mustBeat: "Stichzwang: Du musst die höchste Karte der angespielten Farbe schlagen.",
        mustTrump: "Stichzwang: Du musst stechen, da du die Farbe nicht bedienen kannst.",
        heartsLocked: "Du darfst kein Herz anspielen, solange es nicht das Einzige ist, was dir bleibt.",
      },
      gameOver: "Spiel Beendet",
      difficulty: {
        label: "Schwierigkeit",
        easy: "Leicht",
        normal: "Normal",
        hard: "Schwer",
        expert: "Experte",
      },
      start: "Spiel Starten",
      resume: {
        title: "Unvollendetes Spiel",
        body: "Du hast ein laufendes Spiel. Fortsetzen, oder ein neues starten?",
        resume: "Spiel Fortsetzen",
        startNew: "Neues Spiel Starten",
      },
      handComplete: {
        title: "Hand {{number}} Beendet",
        continue: "Weiter",
      },
      scoreboard: {
        title: "Punktetabelle",
        viewButton: "Punktetabelle Ansehen",
        backToTable: "Zurück zum Tisch",
        total: "Gesamt",
        negativeSubtotal: "Negative Zwischensumme",
        positiveSubtotal: "Positive Zwischensumme",
        winner: "{{name}} gewinnt!",
        tie: "Unentschieden: {{names}}",
        rule: {
          noTricks: "-20/Stich",
          noHearts: "-20/Herz",
          noGentlemen: "-30/Karte",
          noLady: "-50/Karte",
          noKingOfHearts: "-160",
          noLastTwo: "-90 x2",
          positiveUp: "+25/Stich",
          positiveDown: "325-75/Stich",
        },
      },
    },
  },
};
